dist: bionic
sudo: true
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.65.3/hugo_extended_0.65.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.65.3_Linux-64bit.deb
script:
  - hugo
  - cd public
  - touch ~/.git-credentials
  - chmod 0600 ~/.git-credentials
  - echo $GITHUB_AUTH_SECRET > ~/.git-credentials
  - git config credential.helper store
  - git config user.email "millenito-blog-bot@users.noreply.github.com"
  - git config user.name "millenito-blog-bot"
  - git add .
  - git commit --message "Travis: Rebuild site"
  - git push --force origin HEAD:master

deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
