dist: bionic
sudo: true
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.65.3/hugo_extended_0.65.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.65.3_Linux-64bit.deb
script:
  - hugo
  - cd public
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add -A
  - git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"
  - git push origin master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
