dist: bionic
sudo: true
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.65.3/hugo_extended_0.65.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.65.3_Linux-64bit.deb
script:
  - mkdir -p ../public
  - git clone git@github.com:millenito/millenito.github.io.git ../public
  - pwd
  - hugo -d ../public
  - cd ../public
  - pwd
  - ls
  - git status
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add -A
  - git commit -m "Travis rebuild"
  - git push

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
