baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: Lord Maxie Millenito
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: false
enableEmoji: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  imageLogo: images/logo.jpeg
  name: Lord Maxie Millenito
  # description: "\"*Stay hungry. Stay foolish*\" <br>-<small>Steve Jobs</small>"
  description: "GNU/Linux & Software Engineering enthusiasts"
  homeMetaContent: "IT, GNU/Linux, software engineering enthusiasts"
  footer: Dibuat menggunakan [Hugo](https://gohugo.io/). Tema dari [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deploy ke [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2 Jan, 2006
  codePenUser: someUser
  github: millenito
  gitlab: millenito
  email: wownito31@gmail.com
  linkedin:
  telegram:
  twitter:
  instagram: millenito_
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
